src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    private function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
        return __DIR__.'/../../public/uploads/img';
    }

    public function getFilePath()
    {
        return 'uploads/img/'.$this->getUrl();
    }

    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 2, max = 200, minMessage="Your first name must be at least {{ limit }} characters", 
     * maxMessage="Your first name can't be more than {{ limit }} characters")
     */
    private $alt;

    /**
     * @Assert\Image()
     */
    private $file;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Ads", inversedBy="image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Ad;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getAd(): ?Ads
    {
        return $this->Ad;
    }

    public function setAd(Ads $Ad): self
    {
        $this->Ad = $Ad;

        return $this;
    }

    public function getFile(): ?Ads
    {
        return $this->file;
    }

      // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard, après que le persist ait vraiment fonctionné
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if ($this->file !== null)
        {
            $this->url = uniqid() . '.' . $this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function postUpload()
    {
        $this->removeOldFile();

        if ($this->file !== null)
        {
            $name = $this->file->getClientOriginalName();
            $this->file->move($this->getUploadDir(), $this->url);
        }
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $this->removeOldFile();
    }

    /* work with $this->url instead of $this->tempFilename */
    /* Wouldn't work if we would have needed the old ID because post the ID is back at 0 */
    public function removeOldFile()
    {
        if ($this->tempFilename !== null)
        {
            $oldFile = $this->getUploadDir().'/'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
    }
}

src/Controller/KijijiController.php
<?php

namespace App\Controller;

//I have no ideas

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
//Routes annotations
use Symfony\Component\Routing\Annotation\Route;
//Get the url elements
use Symfony\Component\HttpFoundation\Request;
//Sessions
use Symfony\Component\HttpFoundation\Session\SessionInterface;

use Symfony\Component\EventDispatcher\EventDispatcherInterface;

use Symfony\Component\Form\FormError;

use App\Form\AdsType;
use App\Form\AdsEditType;

use Psr\Log\LoggerInterface;

use App\Entity\Ads;
use App\Entity\User;
use App\Entity\Tags;
use App\Entity\Comments;
use App\Events\AdDeleted;
use App\Services\AntiSpam;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
* @Route("/kijiji", name="kijiji_")
*/
class KijijiController extends AbstractController
{
    /**
     * @Route("/{_locale<en|fr>}/{page<\d+>}", defaults={"_locale": "en", "page": "1"}, name="index")
     */
    public function index($page, Request $request, SessionInterface $session, LoggerInterface $logger, AntiSpam $as)
    {
        $logger->info('LOG #1 LOL');



        if ($page < 1) {
            throw $this->createNotFoundException('Page "' . $page . '" inexistante.');
        }

        $search = $request->query->get('search');

        $adsRepository = $this->getDoctrine()->getRepository(Ads::class);
        //$listAds = $adsRepository->findByLimitJointedToUserAndComments(0, 5);
        //$listAds = $adsRepository->findAllBySearch('as');
        //$listAds = $adsRepository->findAllByUser($this->getDoctrine()->getRepository(Users::class)->find(1));
        //$listAds = $adsRepository->findAllByUser(1);
        /*
        $listAds = $adsRepository->findBy([
            'user' => 1, 'id' => '4'
            //'user' => $this->getDoctrine()->getRepository(Users::class)->find(1),
        ], ['id' => 'ASC']);
*/
        //$listAds = array($adsRepository->findOneByUser($this->getDoctrine()->getRepository(Users::class)->find(1)));
        //$listAds = $adsRepository->findByTitle('An ad title');
        //$listAds = $adsRepository->myFind();
        $listAds = $adsRepository->getAdsWithCategories(array('Cat3', 'Cat2'));

        return $this->render('kijiji/index.html.twig', ['search' => $search, 'listAds' => $listAds, 'nbAds' => count($listAds)]);
    }

    /**
     * @Route("/{_locale<en|fr>}/view/{id<\d+>}", defaults={"_locale": "en"}, name="view")
     */
    public function view($id)
    {
        if ($id > 0) {
            $ad = $this->getDoctrine()->getRepository(Ads::class)->findOneBy([
                'id' => $id
            ]);

            if ($ad) {
                $commentsCount = $this->getDoctrine()->getRepository(Comments::class)->countCommentsPerAd($ad);
                return $this->render('kijiji/view.html.twig', ['ad' => $ad, 'commentsCount' => $commentsCount]);
            }
        }

        return $this->redirectToRoute('kijiji_index');
    }

    /**
     * @Route("/{_locale<en|fr>}/add/{id<\d+>}", defaults={"_locale": "en", "id": "0"}, name="add")
     */
    public function add($id, Request $request, LoggerInterface $logger)
    {
        $em = $this->getDoctrine()->getManager();
        $form = null;

        if ($id > 0) {
            $ad = $em->getRepository(Ads::class)->find($id);

            if (!$ad) {
                $ad = new Ads();
            }

            $form = $this->createForm(AdsEditType::class, $ad);
        } else {
            $ad = new Ads();
            $form = $this->createForm(AdsType::class, $ad);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ad = $form->getData();
            $agreeTerms = $form->get('agreeTerms')->getData();

            if ($ad->getTitle() == '123') {
                $error = new FormError("Please don't put 123 as a title");
                $form->get('title')->addError($error);
                $this->addFlash('error', 'Please fill all the fields');
            } else {
                if ($agreeTerms) {
                    $em = $this->getDoctrine()->getManager();
                    $user = $this->getDoctrine()->getRepository(User::class)->find(1);

                    //$ad->getImage()->upload($logger);

                    if ($user) {
                        $ad->setUser($user);
                        foreach ($ad->getTags() as $tag) {
                            if (($persistedTag = $em->getRepository(Tags::class)->findOneByName($tag->getName())) != null) {
                                $ad->removeTag($tag);

                                $tag = $persistedTag;
                            }
                            $tag->addAd($ad);
                            $em->persist($tag);
                            $em->flush();

                            $ad->addTag($tag);
                        }
                        $em->persist($ad);
                        $em->flush();

                        return $this->redirectToRoute('kijiji_view', ['id' => $ad->getId()]);
                    } else {
                        $this->addFlash('error', 'Unexpected error');
                    }
                } else {
                    $error = new FormError("Please agree the terms");
                    $form->get('agreeTerms')->addError($error);
                    $form->addError($error);
                    $this->addFlash('error', 'Please fill all the fields');
                }
            }
        } else {
            if ($form->isSubmitted() && !$form->isValid()) {
                $error = new FormError("There's errors in the form");
                $form->addError($error);
            }
        }

        return $this->render('kijiji/add.html.twig', array('form' => $form->createView()));
    }

    /**
     * @Route("/delete/{id<\d+>}", name="delete")
     *
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete($id, Request $request, EventDispatcherInterface $edi)
    {
        $em = $this->getDoctrine()->getManager();
        $ad = $em->getRepository(Ads::class)->find($id);

        if ($ad) {
            $form = $this->get('form.factory')->create();

            //$event = new AdDeleted($ad);
            //$edi->dispatch(AdDeleted::NAME, $event);
            if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
                $em->remove($ad);
                $em->flush();

                $this->addFlash('info', 'Ad succefully deleted');

                return $this->redirectToRoute('kijiji_index');
            }

            return $this->render('kijiji/delete.html.twig', ['ad' => $ad, 'form' => $form->createView()]);
        }

        return $this->redirectToRoute('kijiji_index');
    }

    /**
     * @Route("/file/{filename}.{_format<txt|xml|jpg|jpeg>}", name="file")
     */
    public function getFile($filename, $_format)
    {
        return $this->render('../../public/files/' . $filename . '.' . $_format);
    }

    /**
     * @Route("/menu/{limit}", defaults={"limit": 4}, name="menu")
     */
    public function menu($limit)
    {
        $listAds = array(
            array('id' => 2, 'title' => 'Recherche ' . $limit . ' développeurs Symfony'),
            array('id' => 5, 'title' => 'Mission de webmaster'),
            array('id' => 9, 'title' => 'Offre de stage webdesigner')
        );

        return $this->render('kijiji/_menu.html.twig', ['ads' => $listAds]);
    }
}

templates/kijiji/_form.html.twig
{% block form_body %}
	{{ form_start(form) }}
		{# form_widget(form) #}

		{{ form_errors(form) }}
		{% if form.title is defined %}
			<div class="form-group {{ form.title.vars.errors.count() > 0 ? 'has-error' }}">
				<i class="fa fa-calendar"></i> {{ form_label(form.title) }}
				{{ form_widget(form.title) }}
				<small>{{ form_help(form.title) }}</small>
				<div class="form-error has-error">
			        {{ form_errors(form.title) }}
			    </div>
			</div>
		{% endif %}
		
		{{ form_row(form.description, {'label_attr': {'class': 'foo'}}) }}

		{{ form_row(form.tags) }}
			<a href="#" id="add_tag" class="btn btn-default">Add a category</a>

		{{ form_rest(form) }}


		<input type="submit" class="btn" value="Create" />
	{{ form_end(form) }}
{% endblock %}

{% block form_javascript %}
	<script type="text/javascript">
		$(document).ready(function() {
			// On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
			var $container = $('div#ads_tags');

			if ($container.attr('data-prototype') == null) {
				$container = $('div#ads_edit_tags');
			}

			// On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
			var index = $container.find(':input').length;

			// On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
			$('#add_tag').click(function(e) {
				addTag($container);

				e.preventDefault(); // évite qu'un # apparaisse dans l'URL
				return false;
			});

			// On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
			if (index == 0) {
				addTag($container);
			} else {
				// S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
				$container.children('div').each(function() {
					addDeleteLink($(this));
				});
			}

			// La fonction qui ajoute un formulaire CategoryType
			function addTag($container) {
				// Dans le contenu de l'attribut « data-prototype », on remplace :
				// - le texte "__name__label__" qu'il contient par le label du champ
				// - le texte "__name__" qu'il contient par le numéro du champ
				var template = $container.attr('data-prototype')
					.replace(/__name__label__/g, 'Tag n°' + (index+1))
					.replace(/__name__/g,        index)
				;

				// On crée un objet jquery qui contient ce template
				var $prototype = $(template);

				// On ajoute au prototype un lien pour pouvoir supprimer la catégorie
				addDeleteLink($prototype);

				// On ajoute le prototype modifié à la fin de la balise <div>
				$container.append($prototype);

				// Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
				index++;
			}

				// La fonction qui ajoute un lien de suppression d'une catégorie
			function addDeleteLink($prototype) {
				// Création du lien
				var $deleteLink = $('<a href="#" class="btn btn-danger">Delete</a>');

				// Ajout du lien
				$prototype.append($deleteLink);

					// Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
				$deleteLink.click(function(e) {
					$prototype.remove();

					e.preventDefault(); // évite qu'un # apparaisse dans l'URL
					return false;
				});
			}
		});
	</script>
{% endblock %}

templates/kijiji/_form_theme.html.twig
{% use 'bootstrap_3_layout.html.twig' %}

{% block textarea_widget %}
    <div class="some-custom-class">
        {{ parent() }}
    </div>
{% endblock %}

templates/kijiji/_menu.html.twig
{% for ad in ads %}
	<p><a href="{{ path('kijiji_view', {'id': ad.id}) }}">{{ ad.title }}</a></p>
{% endfor %}

templates/kijiji/add.html.twig
{% extends "layout.html.twig" %}
{% use "kijiji/_form.html.twig" %}

{% block body %}
	<h2>
		{% if ad is defined %}
			Edit
		{% else %}
			Add
		{% endif %}
	</h2>
		
	{% block form_body %}
		{{ parent() }}
		<h1>Form end</h1>
	{% endblock %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ block('form_javascript') }}
{% endblock %}

templates/kijiji/delete.html.twig
{% extends "layout.html.twig" %}

{% block body %}

<h1>Delete an ad</h1>

<p>Are you sure you want to delete the ad: {{ ad.title }}</p>

{{ form_start(form) }}


{{ form_rest(form) }}

<a href="{{ path('kijiji_view', {'id': ad.id}) }}" class="btn btn-default"><i class="glyficon glyficon-chevron-left"></i>Go back</a>
<input type="submit" class="btn" value="Delete" />

{{ form_end(form) }}
{% endblock %}

templates/kijiji/index.html.twig
{% extends "layout.html.twig" %}

{% block title %}{{ parent() }} - Index{% endblock %}

{% block body %}
    <h2>Ads list ({{ nbAds }})</h2>

    {% for ad in listAds %}
    	<h3>{{ ad.title }}</h3>
    	<p>
    		{{ ad.description }}
    	</p>
    {% else %}
    	<p>No ad found</p>
    {% endfor %}
{% endblock %}

templates/kijiji/view.html.twig
{% extends "layout.html.twig" %}

{% block body %}

	<img src="{{ asset(ad.image.filePath) }}" alt="{{ ad.image.alt }}" />
	<h3>
		{{ ad.title }}
	</h3>

	<p>
		{{ ad.description }}
	</p>

	<h4>
		Comment ({{ commentsCount }}):
	</h4>

	<p>
		<a href="{{ path('kijiji_index') }}" class="btn btn-default"><i class="glyficon glyficon-chevron-left"></i>Return</a>
		<a href="{{ path('kijiji_add', {'id': ad.id}) }}" class="btn btn-default"><i class="glyficon glyficon-edit"></i>Edit</a>
		<a href="{{ path('kijiji_delete', {'id': ad.id}) }}" class="btn btn-default"><i class="glyficon glyficon-trash"></i>Delete</a>
	</p>
{% endblock %}